Vselkin
luisarcila00/BookingParking-C3G18PROYECTOG3 pull request #17
Opened 2021-09-30 03:03 UTC by earamirezba

por favor agregar vista no le borre los logos

2021-09-30 03:05 UTC, luisarcila00 requested changes
agregar a gitignore los node_modules

2021-09-30 03:16 UTC, earamirezba commented
agregado a gitignore los node_modules (en realidad borrado 👯 )

2021-09-30 03:17 UTC, earamirezba commented
> agregar a gitignore los node_modules

agregado a gitignore los node_modules (en realidad borrado 👯 )

2021-09-30 03:19 UTC, luisarcila00 approved these changes
aceptado

2021-09-30 03:25 UTC, luisarcila00 approved these changes
aprobado

2021-09-30 03:25 UTC, merged

2021-10-12 03:20 UTC, earamirezba commented
padre nuestro que estas en los cielos... por favor aprueban

2021-10-12 03:21 UTC, earamirezba commented
listo